//! Differential for `BigFloat::bi`, `ai_prime`, `bi_prime`. MPFR
//! has no `Bi`/`Ai′`/`Bi′`, so the oracle is a checked-in
//! authoritative reference table (generated by `mpmath`
//! `airybi/airyai(.,1)/airybi(.,1)` at 80 digits — the primary-source
//! recipe used for the slice-6m references; treated as a fact)
//! parsed by the bit-exact decimal parser, plus the Wronskian
//! cross-tie `Ai·Bi′ − Ai′·Bi = 1/π` (DLMF 9.2.7) and a
//! high-precision self-consistency sweep.
//!
//! Tolerance `p − 2` bits (the `differential_si` posture; pfloat has
//! no Ziv correct-rounding yet). Precisions capped at 256: each
//! evaluation drives the gamma kernel twice, so p=1024 over the full
//! table is impractical here — the p=1024 path is pinned by the
//! airy-module unit tests (boundary constants and the Wronskian to
//! ~176 bits at p=200).

#![cfg(all(unix, feature = "differential-mpfr"))]

mod differential;

use differential::{next_i64_in, sweep_size, TRANSCENDENTAL_PRECISIONS};
use pfloat::{BigFloat, RoundingMode};

fn close_within(a: &BigFloat, b: &BigFloat, bits: u32) -> bool {
    let (diff, _) = a.sub(b, RoundingMode::NearestEven);
    let abs = diff.abs();
    if abs.is_zero() {
        return true;
    }
    let p = a.precision().max(b.precision());
    let two = BigFloat::try_from_i64_exact(2, p).unwrap();
    let mut bound = b.abs();
    if bound.is_zero() {
        bound = BigFloat::try_from_i64_exact(1, p).unwrap();
    }
    for _ in 0..bits {
        bound = bound.div(&two, RoundingMode::NearestEven).0;
    }
    matches!(
        abs.partial_cmp(&bound).0,
        Some(core::cmp::Ordering::Less | core::cmp::Ordering::Equal)
    )
}

fn at(num: i64, den: i64, p: u32) -> BigFloat {
    let n = BigFloat::try_from_i64_exact(num, p).unwrap();
    if den == 1 {
        n
    } else {
        n.div(
            &BigFloat::try_from_i64_exact(den, p).unwrap(),
            RoundingMode::NearestEven,
        )
        .0
    }
}

/// `(num, den, Bi, Ai′, Bi′)`. Source: `mpmath`
/// `airybi(S(num)/den)`, `airyai(.,1)`, `airybi(.,1)` at 80 digits
/// (mpmath backend); treated as a mathematical fact.
const BI_TABLE: &[(i64, i64, &str, &str, &str)] = &[
    (
        1,
        2,
        "0.85427704310315549330004879879524318085678740050473962693400874155140856462932527",
        "-0.22491053266468389313599699032858321482502963561089283713628595572076802785984971",
        "0.54457256414059230182716401821782332565452889823188714409494593932979241562751259",
    ),
    (
        1,
        1,
        "1.2074235949528712594363788170282869953853489446444425375386209716816173490265505",
        "-0.15914744129679321278750025249722968657388920151161096941519952148917338346800212",
        "0.93243593339277563295945145367443534426956537523862839549286991203857010532123599",
    ),
    (
        2,
        1,
        "3.2980949999782147102806044252234524220039759634036207876829235448371591473109856",
        "-0.053090384433653631703999185878703491248560990045877992630402966177619905319596729",
        "4.1006820499328898893820340791779352943902446137751371198377091895905458899367456",
    ),
    (
        7,
        2,
        "33.055506754611479414257312981921794686126627814372485501095128632606221286795917",
        "-0.0050044139679525828320302496788383679071627837754297473980998742604814295900792575",
        "59.164319581360987034574212179522460252906334306332021722938314192626462729962311",
    ),
    (
        5,
        1,
        "657.79204417117118244108057887444387855631240632928685708736325363044256137276056",
        "-0.00024741389086846247600023617206305060565583396538047719924857898736710086275314138",
        "1435.8190802179825186717212380046182982657156833717445886528393888369784985004274",
    ),
    (
        -1,
        1,
        "0.10399738949694461188868999097859914463701811139252397243525697323463815837816076",
        "-0.010160567116645209395045469845357561841890395466670664105399929722891819066723244",
        "0.59237562642279235081677922918160097327679588336736290578207199394829879790742334",
    ),
    (
        -2,
        1,
        "-0.41230258795639848808323405461146104203453483447240472882387696427537966167538128",
        "0.61825902074169104140626429133247528291577794512414694215989776654557281467155841",
        "0.2787951669211695226850975694109832414030005934516310002397323516499229052306789",
    ),
    (
        -5,
        1,
        "-0.13836913490160057685002917560262372343954017874438689724780306584618010715135073",
        "0.32719281855444313679487867742662919792754024187630071991195170616424555149328004",
        "0.77841177300189924609442320990401745580983676576305905484904216547740627790797169",
    ),
    (
        -7,
        2,
        "0.16893983748105861184344276954094326991156224392630407091582353795179331703871671",
        "-0.34344343345404814628793737409869885709419422095871329426401727566603086857355086",
        "-0.69311628490728880175244361267058046269970266801497849534369683134348941777758447",
    ),
    (
        -9,
        2,
        "0.25387265769693263680052445530702343550032127764528567391233424056352852024354422",
        "-0.52336253231574770070849547927389065148526500230703423759820045079861543005023175",
        "0.63474476777366370973332541226720061799901215221799428431106767106637338117699828",
    ),
];

#[test]
fn bi_family_matches_authoritative_table() {
    for &p in TRANSCENDENTAL_PRECISIONS.iter().filter(|&&p| p <= 256) {
        for &(num, den, bi_s, aip_s, bip_s) in BI_TABLE {
            let x = at(num, den, p);
            let (bi, _) = x.bi(RoundingMode::NearestEven);
            let (aip, _) = x.ai_prime(RoundingMode::NearestEven);
            let (bip, _) = x.bi_prime(RoundingMode::NearestEven);
            for (got, refstr, name) in [
                (&bi, bi_s, "Bi"),
                (&aip, aip_s, "Ai'"),
                (&bip, bip_s, "Bi'"),
            ] {
                let want = BigFloat::parse_str(refstr, p, RoundingMode::NearestEven)
                    .unwrap()
                    .0;
                assert!(
                    close_within(got, &want, p - 2),
                    "{name}({num}/{den}) at p={p}: got {got}, want {want}"
                );
            }
        }
    }
}

#[test]
fn wronskian_identity_holds() {
    // Ai·Bi′ − Ai′·Bi = 1/π for every x (DLMF 9.2.7): the primary
    // cross-tie binding Ai′/Bi′, which have no independent oracle.
    // 1/π to 85 digits (mpmath; treated as a fact), the airy-module
    // unit-test approach — the crate exposes no public π accessor.
    const INV_PI: &str =
        "0.3183098861837906715377675267450287240689192914809128974953346881177935952684530701802";
    for &p in TRANSCENDENTAL_PRECISIONS.iter().filter(|&&p| p <= 256) {
        let inv_pi = BigFloat::parse_str(INV_PI, p, RoundingMode::NearestEven)
            .unwrap()
            .0;
        for &(num, den, _, _, _) in BI_TABLE {
            let x = at(num, den, p);
            let (ai, _) = x.ai(RoundingMode::NearestEven);
            let (bi, _) = x.bi(RoundingMode::NearestEven);
            let (aip, _) = x.ai_prime(RoundingMode::NearestEven);
            let (bip, _) = x.bi_prime(RoundingMode::NearestEven);
            let (t1, _) = ai.mul(&bip, RoundingMode::NearestEven);
            let (t2, _) = aip.mul(&bi, RoundingMode::NearestEven);
            let (w, _) = t1.sub(&t2, RoundingMode::NearestEven);
            assert!(
                close_within(&w, &inv_pi, p - 8),
                "Wronskian at {num}/{den}, p={p}: got {w}"
            );
        }
    }
}

#[test]
fn bi_self_consistent() {
    // Bi at p must agree with Bi at p+64 (rounded to p) to p−8 bits:
    // catches regime/algorithm bugs without an external oracle.
    let mut state: u64 = u64::from_le_bytes(*b"pf6nbisc");
    for &p in &[53u32, 113] {
        for _ in 0..sweep_size().min(20) {
            let a = next_i64_in(&mut state, -8, 8);
            let lo = {
                let (r, _) = at(a, 1, p).bi(RoundingMode::NearestEven);
                r
            };
            let hi = {
                let (r, _) = at(a, 1, p + 64).bi(RoundingMode::NearestEven);
                r.round_to_precision(p, RoundingMode::NearestEven)
                    .unwrap()
                    .0
            };
            assert!(
                close_within(&lo, &hi, p - 8),
                "Bi({a}) self-consistency at p={p}: lo={lo} hi={hi}"
            );
        }
    }
}
