//! pfloat's binary64 elementary kernels round to the same binary64
//! result as the upstream CORE-MATH project's correctly-rounded
//! implementations across a corpus of hard-to-round cases.
//!
//! Provenance: inputs are transcribed from CORE-MATH's per-function
//! `.wc` worst-case-rounding files (MIT-licensed, see
//! `docs/lefevre-muller-corpus-provenance.md` for the lineage and
//! the verbatim CORE-MATH copyright/license header carried into
//! `tests/differential/lefevre_muller_data.rs`); expected outputs
//! are computed by `scripts/extract_lefevre_muller.py` via mpmath
//! at 200-bit working precision and rounded to binary64 under
//! `NearestEven`, not transcribed from CORE-MATH.
//!
//! This test runs without `--features=differential-mpfr`: it does
//! not query MPFR at test time. The "differential" filename matches
//! pfloat's tests/differential_*.rs naming convention (the corpus
//! IS a comparison against an independent oracle, just one that has
//! been pre-evaluated rather than running live). The conformance
//! script counts this file as one more differential lane in the
//! per-bucket gate.
//!
//! The bridge from `f64` (the corpus's input type) to `BigFloat`
//! goes through Rust's shortest-round-trip decimal formatter and
//! `BigFloat::parse_str`. At `p = 53` with `NearestEven`, the
//! parser is correctly rounded for any decimal that round-trips
//! through an `f64`, so the constructed `BigFloat` is bit-exact
//! the input. pfloat's kernel then runs at `p = 53` (binary64
//! precision) under its 64-bit working-precision guard; the
//! returned `BigFloat` is the kernel's claim for the
//! correctly-rounded binary64 result. Equality between two
//! `BigFloat`s at the same precision is bit-equality (`#[derive(Eq,
//! PartialEq)]` on `BigFloat` is the rounded-representation
//! identity); the assertion catches both a wrong sign and a wrong
//! last bit.

#![cfg(all(feature = "exp-log", feature = "trig"))]

use pfloat::{BigFloat, RoundingMode};

// Hard-to-round cases live in `tests/differential/lefevre_muller_data.rs`
// (auto-generated by `scripts/extract_lefevre_muller.py`). The
// generator emits `pub const <NAME>_CASES: &[Case]` for each
// function pfloat covers under the elementary surface.
include!("differential/lefevre_muller_data.rs");

const NE: RoundingMode = RoundingMode::NearestEven;

/// Build a `BigFloat` at `p = 53` that represents the binary64
/// value `x` exactly.
///
/// Rust's `format!("{:?}", x)` produces the shortest decimal that
/// round-trips through `f64`; parsing that decimal at `p = 53`
/// under `NearestEven` recovers the original `f64` bit-exactly.
fn bf53_of(x: f64) -> BigFloat {
    let s = format!("{x:?}");
    let (bf, _status) =
        BigFloat::parse_str(&s, 53, NE).expect("finite binary64 has a parseable shortest decimal");
    bf
}

/// One hard-to-round case asserted: the kernel applied at
/// `p = 53` under `NearestEven` matches the precomputed expected
/// output bit-for-bit.
fn check<F>(name: &str, kernel: F, case: &Case)
where
    F: Fn(&BigFloat) -> (BigFloat, pfloat::Status),
{
    let (input_bits, expected_bits) = *case;
    let input = f64::from_bits(input_bits);
    let expected = f64::from_bits(expected_bits);

    let bf_input = bf53_of(input);
    let (bf_result, _status) = kernel(&bf_input);
    let bf_expected = bf53_of(expected);

    assert_eq!(
        bf_result, bf_expected,
        "{name}({input:e}) [input bits {input_bits:#018x}] \
         produced {bf_result:?}, expected {bf_expected:?} \
         [expected bits {expected_bits:#018x}]"
    );
}

#[test]
fn exp_corpus() {
    for case in EXP_CASES {
        check("exp", |x| x.exp(NE), case);
    }
}

#[test]
fn ln_corpus() {
    for case in LN_CASES {
        check("ln", |x| x.ln(NE), case);
    }
}

#[test]
fn sin_corpus() {
    for case in SIN_CASES {
        check("sin", |x| x.sin(NE), case);
    }
}

#[test]
fn cos_corpus() {
    for case in COS_CASES {
        check("cos", |x| x.cos(NE), case);
    }
}

#[test]
fn tan_corpus() {
    for case in TAN_CASES {
        check("tan", |x| x.tan(NE), case);
    }
}

#[test]
fn atan_corpus() {
    for case in ATAN_CASES {
        check("atan", |x| x.atan(NE), case);
    }
}

#[test]
fn asin_corpus() {
    for case in ASIN_CASES {
        check("asin", |x| x.asin(NE), case);
    }
}

#[test]
fn acos_corpus() {
    for case in ACOS_CASES {
        check("acos", |x| x.acos(NE), case);
    }
}

#[test]
fn exp2_corpus() {
    for case in EXP2_CASES {
        check("exp2", |x| x.exp2(NE), case);
    }
}

#[test]
fn exp10_corpus() {
    for case in EXP10_CASES {
        check("exp10", |x| x.exp10(NE), case);
    }
}

#[test]
fn expm1_corpus() {
    for case in EXPM1_CASES {
        check("expm1", |x| x.expm1(NE), case);
    }
}

#[test]
fn log1p_corpus() {
    for case in LOG1P_CASES {
        check("log1p", |x| x.log1p(NE), case);
    }
}

#[test]
fn sinh_corpus() {
    for case in SINH_CASES {
        check("sinh", |x| x.sinh(NE), case);
    }
}

#[test]
fn cosh_corpus() {
    for case in COSH_CASES {
        check("cosh", |x| x.cosh(NE), case);
    }
}

#[test]
fn asinh_corpus() {
    for case in ASINH_CASES {
        check("asinh", |x| x.asinh(NE), case);
    }
}

#[test]
fn acosh_corpus() {
    for case in ACOSH_CASES {
        check("acosh", |x| x.acosh(NE), case);
    }
}

#[test]
fn atanh_corpus() {
    for case in ATANH_CASES {
        check("atanh", |x| x.atanh(NE), case);
    }
}

#[cfg(feature = "specials")]
#[test]
fn erf_corpus() {
    for case in ERF_CASES {
        check("erf", |x| x.erf(NE), case);
    }
}

#[cfg(feature = "specials")]
#[test]
fn erfc_corpus() {
    for case in ERFC_CASES {
        check("erfc", |x| x.erfc(NE), case);
    }
}
