//! pfloat's binary64 elementary kernels round to the same binary64
//! result as the upstream CORE-MATH project's correctly-rounded
//! implementations across a corpus of hard-to-round cases.
//!
//! Provenance: inputs are transcribed from CORE-MATH's per-function
//! `.wc` worst-case-rounding files (MIT-licensed, see
//! `docs/lefevre-muller-corpus-provenance.md` for the lineage and
//! the verbatim CORE-MATH copyright/license header carried into
//! `tests/differential/lefevre_muller_data.rs`); expected outputs
//! are computed by `scripts/extract_lefevre_muller.py` via mpmath
//! at 200-bit working precision and rounded to binary64 under
//! `NearestEven`, not transcribed from CORE-MATH.
//!
//! This test runs without `--features=differential-mpfr`: it does
//! not query MPFR at test time. The "differential" filename matches
//! pfloat's tests/differential_*.rs naming convention (the corpus
//! IS a comparison against an independent oracle, just one that has
//! been pre-evaluated rather than running live). The conformance
//! script counts this file as one more differential lane in the
//! per-bucket gate.
//!
//! The bridge from `f64` (the corpus's input type) to `BigFloat`
//! goes through `bf53_of_bits`, which constructs the `p = 53`
//! `BigFloat` from the binary64 bit pattern bit-exact via integer
//! mantissa plus a chain of power-of-two mul/div scalings. This
//! path handles binary64 subnormals correctly, where the
//! shortest-decimal route would round at the `p = 53` `BigFloat`'s
//! finer-than-binary64 precision and yield a near-correct but not
//! bit-exact representation. pfloat's kernel then runs at
//! `p = 53` (binary64 precision) through the slice-p1.2 `Ziv`
//! interval-test driver; the returned `BigFloat` is the kernel's
//! claim for the correctly-rounded binary64 result. The assertion
//! converts that `BigFloat` to an `f64` via Rust's standard parser
//! on the value's round-trip decimal, then compares the resulting
//! bit pattern to CORE-MATH's expected output bits. This comparison
//! is the honest surface for the correctly-rounded claim: pfloat
//! and CORE-MATH agree on the binary64 bit pattern for every
//! corpus input.

#![cfg(all(feature = "exp-log", feature = "trig"))]

use pfloat::{BigFloat, RoundingMode, Sign};

// Hard-to-round cases live in `tests/differential/lefevre_muller_data.rs`
// (auto-generated by `scripts/extract_lefevre_muller.py`). The
// generator emits `pub const <NAME>_CASES: &[Case]` for each
// function pfloat covers under the elementary surface.
include!("differential/lefevre_muller_data.rs");

const NE: RoundingMode = RoundingMode::NearestEven;

/// Build a `BigFloat` at `p = 53` that represents the binary64
/// value with the given bit pattern exactly.
///
/// Constructs the value as `m * 2^scale` where `m` is the integer
/// mantissa (53 bits for normal, ≤ 52 bits for subnormal) and
/// `scale` is the binary exponent offset. The scaling is performed
/// via chained `mul`/`div` by `2^30` chunks (exact in `BigFloat`
/// arithmetic since multiplication by an exact power of two
/// shifts the binary exponent without touching the mantissa); the
/// final result is bit-exact the source binary64 even for
/// subnormals, where the shortest-decimal route would round at the
/// `p = 53` `BigFloat`'s finer-than-binary64 precision and produce a
/// near-correct but not bit-exact representation.
fn bf53_of_bits(bits: u64) -> BigFloat {
    let sign_neg = (bits >> 63) & 1 == 1;
    let exp_field = ((bits >> 52) & 0x7FF) as i64;
    let mant_field = (bits & 0x000F_FFFF_FFFF_FFFF) as i64;
    let sign = if sign_neg {
        Sign::Negative
    } else {
        Sign::Positive
    };

    if exp_field == 0 && mant_field == 0 {
        return BigFloat::try_new_zero(sign, 53).expect("p=53 valid");
    }
    if exp_field == 0x7FF {
        if mant_field == 0 {
            return BigFloat::try_new_infinity(sign, 53).expect("p=53 valid");
        }
        return BigFloat::try_new_quiet_nan(sign, 53, &[]).expect("p=53 valid");
    }

    let (mantissa_int, scale) = if exp_field == 0 {
        (mant_field, -1074i64)
    } else {
        ((1i64 << 52) | mant_field, exp_field - 1023 - 52)
    };
    let signed_mantissa = if sign_neg {
        -mantissa_int
    } else {
        mantissa_int
    };

    let mut bf =
        BigFloat::try_from_i64_exact(signed_mantissa, 53).expect("53-bit mantissa fits in i64");

    let chunk_bits: u32 = 30;
    let chunk = BigFloat::try_from_i64_exact(1i64 << chunk_bits, 53).expect("2^30 fits");
    let abs = scale.unsigned_abs();
    let q = abs / u64::from(chunk_bits);
    let r = (abs % u64::from(chunk_bits)) as u32;
    for _ in 0..q {
        bf = if scale >= 0 {
            bf.mul(&chunk, NE).0
        } else {
            bf.div(&chunk, NE).0
        };
    }
    if r > 0 {
        let rem = BigFloat::try_from_i64_exact(1i64 << r, 53).expect("small power fits");
        bf = if scale >= 0 {
            bf.mul(&rem, NE).0
        } else {
            bf.div(&rem, NE).0
        };
    }
    bf
}

/// Convert the kernel's `BigFloat` output back to a binary64 bit
/// pattern via Rust's standard f64 parser on the value's
/// round-trip decimal. This is the honest comparison surface for
/// the correctly-rounded claim: pfloat produces the same `f64` bit
/// pattern as CORE-MATH for every corpus input. Handles binary64
/// subnormals correctly (where the `p = 53` `BigFloat`
/// representation is not equal to the parse of the f64's shortest
/// decimal).
fn bf_to_f64_bits(bf: &BigFloat) -> u64 {
    let s = format!("{bf}");
    s.parse::<f64>()
        .expect("BigFloat's Display round-trips through f64")
        .to_bits()
}

/// One hard-to-round case asserted: the kernel applied at
/// `p = 53` under `NearestEven` produces the same binary64 bit
/// pattern as CORE-MATH's expected output.
fn check<F>(name: &str, kernel: F, case: &Case)
where
    F: Fn(&BigFloat) -> (BigFloat, pfloat::Status),
{
    let (input_bits, expected_bits) = *case;
    let input = f64::from_bits(input_bits);

    let bf_input = bf53_of_bits(input_bits);
    let (bf_result, _status) = kernel(&bf_input);
    let result_bits = bf_to_f64_bits(&bf_result);

    assert_eq!(
        result_bits, expected_bits,
        "{name}({input:e}) [input bits {input_bits:#018x}] \
         produced {bf_result:?} [bits {result_bits:#018x}], expected \
         [bits {expected_bits:#018x}]"
    );
}

#[test]
fn exp_corpus() {
    for case in EXP_CASES {
        check("exp", |x| x.exp(NE), case);
    }
}

#[test]
fn ln_corpus() {
    for case in LN_CASES {
        check("ln", |x| x.ln(NE), case);
    }
}

#[test]
fn sin_corpus() {
    for case in SIN_CASES {
        check("sin", |x| x.sin(NE), case);
    }
}

#[test]
fn cos_corpus() {
    for case in COS_CASES {
        check("cos", |x| x.cos(NE), case);
    }
}

#[test]
fn tan_corpus() {
    for case in TAN_CASES {
        check("tan", |x| x.tan(NE), case);
    }
}

#[test]
fn atan_corpus() {
    for case in ATAN_CASES {
        check("atan", |x| x.atan(NE), case);
    }
}

#[test]
fn asin_corpus() {
    for case in ASIN_CASES {
        check("asin", |x| x.asin(NE), case);
    }
}

#[test]
fn acos_corpus() {
    for case in ACOS_CASES {
        check("acos", |x| x.acos(NE), case);
    }
}

#[test]
fn exp2_corpus() {
    for case in EXP2_CASES {
        check("exp2", |x| x.exp2(NE), case);
    }
}

#[test]
fn exp10_corpus() {
    for case in EXP10_CASES {
        check("exp10", |x| x.exp10(NE), case);
    }
}

#[test]
fn expm1_corpus() {
    for case in EXPM1_CASES {
        check("expm1", |x| x.expm1(NE), case);
    }
}

#[test]
fn log1p_corpus() {
    for case in LOG1P_CASES {
        check("log1p", |x| x.log1p(NE), case);
    }
}

#[test]
fn log2_corpus() {
    for case in LOG2_CASES {
        check("log2", |x| x.log2(NE), case);
    }
}

#[test]
fn log10_corpus() {
    for case in LOG10_CASES {
        check("log10", |x| x.log10(NE), case);
    }
}

#[test]
fn sinh_corpus() {
    for case in SINH_CASES {
        check("sinh", |x| x.sinh(NE), case);
    }
}

#[test]
fn cosh_corpus() {
    for case in COSH_CASES {
        check("cosh", |x| x.cosh(NE), case);
    }
}

#[test]
fn asinh_corpus() {
    for case in ASINH_CASES {
        check("asinh", |x| x.asinh(NE), case);
    }
}

#[test]
fn acosh_corpus() {
    for case in ACOSH_CASES {
        check("acosh", |x| x.acosh(NE), case);
    }
}

#[test]
fn atanh_corpus() {
    for case in ATANH_CASES {
        check("atanh", |x| x.atanh(NE), case);
    }
}

#[test]
fn tanh_corpus() {
    for case in TANH_CASES {
        check("tanh", |x| x.tanh(NE), case);
    }
}

#[cfg(feature = "specials")]
#[test]
fn erf_corpus() {
    for case in ERF_CASES {
        check("erf", |x| x.erf(NE), case);
    }
}

#[cfg(feature = "specials")]
#[test]
fn erfc_corpus() {
    for case in ERFC_CASES {
        check("erfc", |x| x.erfc(NE), case);
    }
}

#[cfg(feature = "specials")]
#[test]
fn gamma_corpus() {
    for case in GAMMA_CASES {
        check("gamma", |x| x.gamma(NE), case);
    }
}

#[cfg(feature = "specials")]
#[test]
fn lgamma_corpus() {
    for case in LGAMMA_CASES {
        check("lgamma", |x| x.lgamma(NE), case);
    }
}
